config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  root 'welcome#index'

  get 'about' => 'welcome#about'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]
  include DestinationsHelper

  # GET /destinations
  # GET /destinations.json
  def index
      if params[:country]
        @destinations = destinations_in_country params[:country]
      else
      @destinations = Destination.all
      end
    @countries = Destination.pluck(:country).uniq.sort
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new

    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @homeland = "Puerto Rico"
    @countries = ['Chile' , 'Bolivia' , 'Croatia']
    @images = ['chili.jpg' , 'bolivia.jpg' , 'croatia.jpg','people.jpg']
  end

  def about
    @background = params[:background]
    @foreground = params[:foreground]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
  def normalize_country(country)
  end

  def destinations_in_country(country)
    destinations = Destination.where(:country => params[:country])
  
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
      <%= f.label :city %><br>
      <%= f.text_field :city, class: "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :country %><br>
      <%= f.text_field :country, class: "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control", rows: "5" %>
    </div>
    <div class="actions form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Destination Wish List</h1>

  <div class="row">
    <% @destinations.each do |destination| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h2><%= destination.city %></h2>
         <h3<%= destination.country %></h3>
         <p><%= destination.description %></p>

         <div class="btn-group">
          <%= link_to 'Show', destination, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-default" %>
          <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Destination', new_destination_path, class: "btn btn-primary" %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<% if notice != nil %>
<div  class="alert alert-success" role="alert"><%= notice %></div>
<% end %>
<h1><%= @destination.city %>, <%= @destination.country %></h1>

<p> <%= @destination.description %></p>

<div class="btn-group">
  <%= link_to 'Edit', edit_destination_path(@destination), class: "btn btn-default" %>
  <%= link_to 'Back', destinations_path, class: "btn btn-default" %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to 'Home', root_path %>
      </li>
      <li>
        <%= link_to 'About', about_path %>
      </li>
      <li>
         <%= link_to 'Destinations', destinations_path, :country => 'United States' %>


      </li>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body><div class="container">
<%= render '/layouts/header' %>

<div class="container">
 <p>Static Countries list hardcoded
    <%= link_to 'All', destinations_path   %> |
    <%= link_to 'United States',controller: "destinations", :country => 'United States' %> |
    <%= link_to 'Canada',controller: "destinations", :country => 'Canada' %></p>



 <p>Dynamic Countries list from database
<% @countries.each do |country| %>
<% url_safe_country = country %>
<%= link_to country, :controller => "destinations", :country => url_safe_country %> |
<% end %></p>




</div>
<%= yield %>

</div></div>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js">
</body>
</html>

app/views/welcome/about.html.erb
<h1>About</h1>
<p>Find me in app/views/welcome/about.html.erb</p>



<p>The color you chose was: </p>


<style>body{background-color:<%= @background %>;color:<%= @foreground %>;}</style>

app/views/welcome/index.html.erb
<h1>Welcome to my Travel Site</h1>
<p>This is my awesome travel site</p>

<%= @homeland %>

<ul>
  <% @countries.each do |country| %>
    <li>&#187;
      <%= country %>
    </li>
  <% end %>
</ul>

<%  @images.each do |image|   %>
    <%= image_tag image %>
  <% end %>